//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DRSEntities : DbContext
    {
        public DRSEntities()
            : base("name=DRSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jct_Dak_BankMaster> Jct_Dak_BankMaster { get; set; }
        public virtual DbSet<Jct_Dak_Cities> Jct_Dak_Cities { get; set; }
        public virtual DbSet<Jct_Dak_Country> Jct_Dak_Country { get; set; }
        public virtual DbSet<Jct_Dak_DeptMaster> Jct_Dak_DeptMaster { get; set; }
        public virtual DbSet<jct_Dak_Email> jct_Dak_Email { get; set; }
        public virtual DbSet<Jct_Dak_Itemtype> Jct_Dak_Itemtype { get; set; }
        public virtual DbSet<Jct_Dak_Party_Detail_Address> Jct_Dak_Party_Detail_Address { get; set; }
        public virtual DbSet<Jct_Dak_Party_Header> Jct_Dak_Party_Header { get; set; }
        public virtual DbSet<Jct_Dak_Party_Sr_No> Jct_Dak_Party_Sr_No { get; set; }
        public virtual DbSet<Jct_Dak_Register_Cheque> Jct_Dak_Register_Cheque { get; set; }
        public virtual DbSet<jct_dak_role> jct_dak_role { get; set; }
        public virtual DbSet<Jct_Dak_Service_Details> Jct_Dak_Service_Details { get; set; }
        public virtual DbSet<Jct_Dak_Service_Mode> Jct_Dak_Service_Mode { get; set; }
        public virtual DbSet<Jct_Dak_State> Jct_Dak_State { get; set; }
        public virtual DbSet<Jct_Dak_Type_Sr_No> Jct_Dak_Type_Sr_No { get; set; }
        public virtual DbSet<JCT_EMP_HOD> JCT_EMP_HOD { get; set; }
        public virtual DbSet<Jct_Dak_Register> Jct_Dak_Register { get; set; }
        public virtual DbSet<Jct_Dak_Register_Recieved> Jct_Dak_Register_Recieved { get; set; }
        public virtual DbSet<JCT_EMP_HOD_Dept> JCT_EMP_HOD_Dept { get; set; }
    }
}
