//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Register_Cheque
    {
        public int TransNo { get; set; }
        public string Inward_No { get; set; }
        public string Cheque_No { get; set; }
        public Nullable<System.DateTime> Cheque_Date { get; set; }
        public string BankName { get; set; }
        public string Payable_At { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Empcode { get; set; }
        public string Created_Hostname { get; set; }
        public string Ip_Address { get; set; }
    }
}
