//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_DeptMaster
    {
        public int TransNo { get; set; }
        public string DEPTCODE { get; set; }
        public string DEPTNAME { get; set; }
        public string Status { get; set; }
    }
}
