//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class jct_dak_role
    {
        public int Trans_No { get; set; }
        public string RoleId { get; set; }
        public string Rolename { get; set; }
        public string empcode { get; set; }
        public string DESCRIPTION { get; set; }
        public string Dept { get; set; }
    }
}
