//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Register
    {
        public int TransNo { get; set; }
        public string Dak_Code { get; set; }
        public string Dak_Type { get; set; }
        public string Inward_No { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> Reference_Date { get; set; }
        public string Party_Code { get; set; }
        public string Dept_Code { get; set; }
        public string Hod_Code { get; set; }
        public string Phone_No { get; set; }
        public string MailTo { get; set; }
        public string DakService_Code { get; set; }
        public string DakService_Type { get; set; }
        public string SUBJECT { get; set; }
        public string Remarks { get; set; }
        public string ConcernedPersonals { get; set; }
        public string Attached_File { get; set; }
        public string Empcode { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_Hostname { get; set; }
        public string Ip_Address { get; set; }
        public string DakService_Mode { get; set; }
        public string Department { get; set; }
        public string PartyAddress_id { get; set; }
        public bool Email_Status { get; set; }
        public string Party_Type { get; set; }
    }
}
