//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class jct_Dak_Email
    {
        public int TransNo { get; set; }
        public string Emp_Code { get; set; }
        public string hod_code { get; set; }
        public string Emp_Name { get; set; }
        public string EMail_ID { get; set; }
    }
}
