//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Register_Recieved
    {
        public int TransNo { get; set; }
        public string Inward_No { get; set; }
        public bool Received_Status { get; set; }
        public string Reply_ReferenceNo { get; set; }
        public Nullable<System.DateTime> Reply_ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Empcode { get; set; }
        public string Created_Hostname { get; set; }
        public string Ip_Address { get; set; }
        public Nullable<bool> Email_Status { get; set; }
    }
}
