//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Party_Sr_No
    {
        public int TransNo { get; set; }
        public string PartyNo { get; set; }
        public string Delimiter { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public string Empcode { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
