//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCT_EMP_HOD
    {
        public int Trans_No { get; set; }
        public string Hod_Code { get; set; }
        public string Hod_Name { get; set; }
        public string Deptcode { get; set; }
        public string Mobile { get; set; }
        public string E_MailID { get; set; }
        public string Flag { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Eff_From { get; set; }
        public Nullable<System.DateTime> Eff_To { get; set; }
    }
}
