//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Service_Details
    {
        public int TransNo { get; set; }
        public string ServiceMode_Code { get; set; }
        public string DakService_Code { get; set; }
        public string DakService_Name { get; set; }
        public string Description { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PhoneNo { get; set; }
        public string Email_Address { get; set; }
        public string Office_Number { get; set; }
        public string FaxNumber { get; set; }
        public string WebSite { get; set; }
        public string STDCode { get; set; }
        public string Logo { get; set; }
        public string Empcode { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_Hostname { get; set; }
        public string Ip_Address { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
    }
}
