//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DakManSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jct_Dak_Party_Detail_Address
    {
        public int TransNo { get; set; }
        public string Party_Type { get; set; }
        public string Party_Code { get; set; }
        public string address_id { get; set; }
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Address_Line_3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zip_No { get; set; }
        public string Phone_No { get; set; }
        public string Telex_No { get; set; }
        public string Fax_No { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Empcode { get; set; }
        public string Created_Hostname { get; set; }
        public string Ip_Address { get; set; }
    }
}
